services:
  vulnerability-tests:
    container_name: vt
    environment:
      STORAGE_PATH: /var/lib/openvas/22.04/vt-data/nasl
    image: greenbone/vulnerability-tests:latest
    volumes:
      - vt_data_vol:/mnt

  data-objects:
    container_name: data-objects
    image: greenbone/data-objects:latest
    volumes:
      - data_objects_vol:/mnt

  scap-data:
    container_name: scap
    image: greenbone/scap-data:latest
    volumes:
      - scap_data_vol:/mnt

  cert-bund-data:
    container_name: cert
    image: greenbone/cert-bund-data:latest
    volumes:
      - cert_data_vol:/mnt

  dfn-cert-data:
    container_name: dnf-cert
    depends_on:
      - cert-bund-data
    image: greenbone/dfn-cert-data:latest
    volumes:
      - cert_data_vol:/mnt

  gpg-data:
    container_name: gpg
    image: greenbone/gpg-data:latest
    volumes:
      - gpg_data_vol:/mnt

  report-formats:
    container_name: report-formats
    depends_on:
      - data-objects
    image: greenbone/report-formats:latest
    volumes:
      - data_objects_vol:/mnt

  mqtt-broker:
    container_name: mqtt-broker
    expose:
      - "1883"
    image: greenbone/mqtt-broker:latest
    networks:
      default:
        aliases:
          - mqtt-broker
          - broker
    restart: on-failure

  notus-scanner:
    container_name: notus-scanner
    depends_on:
      - mqtt-broker
      - gpg-data
      - vulnerability-tests
    environment:
      NOTUS_SCANNER_MQTT_BROKER_ADDRESS: mqtt-broker
      NOTUS_SCANNER_PRODUCTS_DIRECTORY: /var/lib/notus/products
    image: greenbone/notus-scanner:stable
    restart: on-failure
    volumes:
      - notus_data_vol:/var/lib/notus
      - gpg_data_vol:/etc/openvas/gnupg

  notus-data:
    container_name: notus-data
    image: greenbone/notus-data:latest
    volumes:
      - notus_data_vol:/mnt
    
  redis-server:
    container_name: redis
    image: greenbone/redis-server:latest
    restart: on-failure
    volumes:
      - redis_socket_vol:/run/redis/

  pg-gvm:
    container_name: postgres
    image: greenbone/pg-gvm:stable
    restart: on-failure
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  gvmd:
    container_name: gvmd
    depends_on:
      pg-gvm:
        condition: service_started
      scap-data:
        condition: service_completed_successfully
      cert-bund-data:
        condition: service_completed_successfully
      dfn-cert-data:
        condition: service_completed_successfully
      data-objects:
        condition: service_completed_successfully
      report-formats:
        condition: service_completed_successfully
    image: greenbone/gvmd:stable
    restart: on-failure
    volumes:
      - gvmd_data_vol:/var/lib/gvm
      - scap_data_vol:/var/lib/gvm/scap-data/
      - cert_data_vol:/var/lib/gvm/cert-data
      - data_objects_vol:/var/lib/gvm/data-objects/gvmd
      - vt_data_vol:/var/lib/openvas/plugins
      - psql_data_vol:/var/lib/postgresql
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql
    
  ospd-openvas:
    container_name: ospd-openvas
    depends_on:
      redis-server:
        condition: service_started
      gpg-data:
        condition: service_completed_successfully
      vulnerability-tests:
        condition: service_completed_successfully
    image: greenbone/ospd-openvas:stable
    init: true
    hostname: ospd-openvas.local
    cap_add:
      - NET_ADMIN # for capturing packages in promiscuous mode
      - NET_RAW # for raw sockets e.g. used for the boreas alive detection
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    command:
      [
        "ospd-openvas",
        "-f",
        "--config",
        "/etc/gvm/ospd-openvas.conf",
        "--mqtt-broker-address",
        "mqtt-broker",
        "--notus-feed-dir",
        "/var/lib/notus/advisories",
        "-m",
        "666"
      ]
    restart: on-failure
    volumes:
      - gpg_data_vol:/etc/openvas/gnupg
      - vt_data_vol:/var/lib/openvas/plugins
      - notus_data_vol:/var/lib/notus
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/

  gvm-tools:
    container_name: gvm-tools
    image: greenbone/gvm-tools
    volumes:
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
    depends_on:
      - gvmd
      - ospd-openvas

  gsa:
    container_name: gsa
    depends_on:
      - gvmd
    expose:
      - "80"
    image: greenbone/gsa:stable
    restart: on-failure
    volumes:
      - gvmd_socket_vol:/run/gvmd

  nginx:
    container_name: nginx
    image: nginx:1.24.0
    ports:
      - 443:443
    volumes:
      - ./gvm.pem:/etc/nginx/certs/gvm.pem
      - ./gvm-key.pem:/etc/nginx/certs/gvm-key.pem
      - ./gvm.conf:/etc/nginx/conf.d/gvm.conf
    depends_on:
      - gsa
      - gvmd
      - ospd-openvas

volumes:
  gpg_data_vol:
  scap_data_vol:
  cert_data_vol:
  data_objects_vol:
  gvmd_data_vol:
  psql_data_vol:
  vt_data_vol:
  notus_data_vol:
  psql_socket_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  redis_socket_vol:
